// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCxnE4SNKl-dhttCHBU4GZrKWqq08Ms2E',
    appId: '1:714741175066:web:35d64d633f8c4f305392a3',
    messagingSenderId: '714741175066',
    projectId: 'munote-21dc4',
    authDomain: 'munote-21dc4.firebaseapp.com',
    storageBucket: 'munote-21dc4.firebasestorage.app',
    measurementId: 'G-H08KD1E2LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-l0PqQdc-pZCWofxgPLPe8eJEY0R90uU',
    appId: '1:714741175066:android:4866fe682a0819325392a3',
    messagingSenderId: '714741175066',
    projectId: 'munote-21dc4',
    storageBucket: 'munote-21dc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8xl6ngjQgq64iTutY5Ni-Bc2sZ--0y_w',
    appId: '1:714741175066:ios:e17299cd0b31f17f5392a3',
    messagingSenderId: '714741175066',
    projectId: 'munote-21dc4',
    storageBucket: 'munote-21dc4.firebasestorage.app',
    iosBundleId: 'com.example.newTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8xl6ngjQgq64iTutY5Ni-Bc2sZ--0y_w',
    appId: '1:714741175066:ios:e17299cd0b31f17f5392a3',
    messagingSenderId: '714741175066',
    projectId: 'munote-21dc4',
    storageBucket: 'munote-21dc4.firebasestorage.app',
    iosBundleId: 'com.example.newTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCxnE4SNKl-dhttCHBU4GZrKWqq08Ms2E',
    appId: '1:714741175066:web:7389547b5f6c827c5392a3',
    messagingSenderId: '714741175066',
    projectId: 'munote-21dc4',
    authDomain: 'munote-21dc4.firebaseapp.com',
    storageBucket: 'munote-21dc4.firebasestorage.app',
    measurementId: 'G-3TZ2F1453R',
  );
}
